import { appendEvent, pendingJobs, updateJob, saveVerdict, getVerdict, getExecution, saveExecution, getEvidence, saveEvidence } from "@/lib/store";
import { selectProviders, collectEvidence } from "@/lib/providers";
import { finalizeEvaluation, readFinalized, submitEvaluation } from "@/lib/genlayer";
import { sha256 } from "@/lib/hash";

export async function processJob(id:string){const jobs=await pendingJobs(50);const job=jobs.find(j=>j.id===id);if(!job)return null;if(new Date(job.expires_at)<new Date()&&!['genlayer_submitted','genlayer_pending','verdict_finalized'].includes(job.status))return updateJob(id,"failed",{errorCode:"job_expired",errorMessage:"The processing deadline elapsed."});
  if(job.status==="payment_settled")return updateJob(id,"planning");
  if(job.status==="planning")return updateJob(id,"providers_selected");
  if(job.status==="providers_selected")return updateJob(id,"evidence_requested");
  if(job.status==="evidence_requested")return updateJob(id,"evidence_collected");
  if(job.status==="evidence_collected")return updateJob(id,"evidence_normalized");
  if(job.status==="evidence_normalized")return updateJob(id,"genlayer_submitted");
  if(job.status==="genlayer_submitted"||job.status==="genlayer_pending"){
    const execution=await getExecution(id);
    const recovered=await readFinalized(job.request_json,execution?.transaction);
    if(recovered){await appendEvent("genlayer.finalized",{jobId:id,decision:recovered.decision,confidence:recovered.confidence,transaction:recovered.genlayerTransaction});await saveVerdict(id,recovered);return updateJob(id,"verdict_finalized");}
    if(execution){const finalized=await finalizeEvaluation(job.request_json,execution.transaction);if(!finalized)return updateJob(id,"genlayer_pending");if(finalized.verdict){const verdict=finalized.verdict;await appendEvent("genlayer.finalized",{jobId:id,decision:verdict.decision,confidence:verdict.confidence,transaction:verdict.genlayerTransaction});await saveVerdict(id,verdict);return updateJob(id,"verdict_finalized");}if(execution.submissionAttempt>=3)return updateJob(id,"failed",{errorCode:"genlayer_consensus_failed",errorMessage:"GenLayer did not finalize a valid contract result after three submissions."});await appendEvent("genlayer.retry",{jobId:id,transaction:execution.transaction,submissionAttempt:execution.submissionAttempt});}
    let evidence=await getEvidence(id);if(!evidence){const providers=await selectProviders(job.request_json,job.max_providers);if(providers.length<2)throw new Error("provider_quorum_unavailable:0/2");await appendEvent("providers.selected",{jobId:id,providerIds:providers.slice(0, job.max_providers).map((provider:any)=>provider.id),candidateCount:providers.length,requiredEvidence:2});evidence=await collectEvidence(job.request_json,providers,id,2);await saveEvidence(id,evidence);await appendEvent("evidence.collected",{jobId:id,providerCount:evidence.length,providerIds:evidence.map((item:any)=>item.providerId),costAtomic:evidence.reduce((sum:any,item:any)=>sum+Number((item as any).costAtomic||0),0)});}if(evidence.length<2||new Set(evidence.map((item:any)=>item.providerId)).size<2)throw new Error(`provider_quorum_unavailable:${evidence.length}/2`);const evidenceJson=JSON.stringify(evidence);const submissionAttempt=(execution?.submissionAttempt??0)+1;await appendEvent("genlayer.payload_prepared",{jobId:id,evidenceContentHash:await sha256(evidenceJson),evidenceBytes:Buffer.byteLength(evidenceJson),evidenceRecords:evidence.length,contract:process.env.GENLAYER_CONTRACT_ADDRESS,method:"submit_case",argumentIndex:3,providerIds:evidence.map((item:any)=>item.providerId)});const submitted=await submitEvaluation(job.request_json,evidence);if(!submitted.transaction){const verdict={decision:"insufficient_evidence" as const,confidence:0,score:0,summary:"GenLayer reporter is not configured.",reasonCodes:["GENLAYER_NOT_CONFIGURED"],evidenceDigest:submitted.evidenceDigest,expiresAt:new Date(Date.now()+5*60_000).toISOString(),genlayerNetwork:"studionet" as const};await saveVerdict(id,verdict);return updateJob(id,"verdict_finalized");}await saveExecution(id,{transaction:submitted.transaction,evidenceDigest:submitted.evidenceDigest,submittedAt:new Date().toISOString(),submissionAttempt});return updateJob(id,"genlayer_pending");}
  if(job.status==="verdict_finalized"&&await getVerdict(id))return updateJob(id,"response_ready");return job;}
export async function processBatch(limit=10){const jobs=await pendingJobs(limit);const results=[];for(const job of jobs){try{results.push(await processJob(job.id));}catch(error){const message=error instanceof Error?error.message:"Unknown processing error";const quorum=message.startsWith("provider_quorum_unavailable");results.push(await updateJob(job.id,"failed",{errorCode:quorum?"provider_quorum_unavailable":"processing_failed",errorMessage:quorum?"Two independent paid providers did not return usable evidence. No GenLayer verdict was submitted.":message}));}}return results;}
export async function runJobToCompletion(id:string){let job=await processJob(id);for(let step=0;step<10&&job&&!['response_ready','failed','refunded'].includes(job.status);step+=1){job=await processJob(id);}return job;}
