"use client";
import { useEffect, useState } from "react";
import { useWallet } from "@/components/wallet-context";

type Props = { title: string; description: string; endpoint: string; product: string; price: string; examples: string[] };
export function RequestWorkbench({ title, description, endpoint, product, price, examples }: Props) {
  const { address, connect, paidFetch } = useWallet();
  const [task, setTask] = useState(examples[0]); const [subject, setSubject] = useState(""); const [criteria, setCriteria] = useState(""); const [jobId, setJobId] = useState(""); const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit() {
    setLoading(true); setError(""); setResult(null);
    try {
      if (!address) { const connected = await connect(); if (!connected) throw new Error("Connect a wallet to authorize the USDC payment."); }
      const response = await paidFetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ task, subject: { address: subject || undefined }, context: { source: "gen-x402-dashboard" }, acceptanceCriteria: criteria.split("\n").filter(Boolean), riskLevel: "medium", clientRequestId: crypto.randomUUID() }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Request failed"); setJobId(body.jobId); setResult(body);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Payment request failed"); } finally { setLoading(false); }
  }
  useEffect(() => { if (!jobId) return; const timer = setInterval(async () => { const response = await fetch(`/api/v1/jobs/${jobId}`); if (!response.ok) return; const body = await response.json(); setResult(body); if (["response_ready", "failed", "refunded"].includes(body.job?.status)) clearInterval(timer); }, 1400); return () => clearInterval(timer); }, [jobId]);
  return <main className="section workbench"><div className="phase-line"><span>PHASE 04</span><i />{product.toUpperCase()} / LIVE DECISION CHANNEL</div><div className="workbench-head"><div><span className="eyebrow">INTELLIGENCE MODULE · {price} USDC</span><h1>{title}</h1><p>{description}</p></div><div className="module-readout"><span>NETWORK</span><b>SEPOLIA / 84532</b><span>CONSENSUS</span><b>STUDIONET</b><span>SETTLEMENT</span><b>x402 EXACT</b></div></div><div className="formLayout"><section className="terminal-card"><div className="terminal-top"><span>REQUEST CONSOLE</span><span>AUTH {address ? "READY" : "REQUIRED"}</span></div><div className="field"><label>01 / TASK OR QUESTION</label><textarea value={task} onChange={e => setTask(e.target.value)} /></div><div className="field"><label>02 / SUBJECT ADDRESS (OPTIONAL)</label><input value={subject} onChange={e => setSubject(e.target.value)} placeholder="0x..." /></div>{product === "Quality Control" && <div className="field"><label>03 / ACCEPTANCE CRITERIA</label><textarea value={criteria} onChange={e => setCriteria(e.target.value)} placeholder="One criterion per line" /></div>}<div className="execute-row"><button className="tech-button primary-action" onClick={submit} disabled={loading || task.length < 10}>{loading ? "PROCESSING" : address ? `AUTHORIZE ${price} USDC` : "CONNECT WALLET TO EXECUTE"}</button><span>NON-CUSTODIAL · SIGNED IN WALLET</span></div>{error && <div className="notice error">{error}</div>}</section><aside className="telemetry-card"><div className="terminal-top"><span>PROCESS TELEMETRY</span><span className="live-dot">● LIVE</span></div><div className="telemetry-steps"><div className="telemetry-step active"><b>01</b><span>Payment authorization</span><em>{address ? "READY" : "WAITING"}</em></div><div className="telemetry-step"><b>02</b><span>Upstream evidence</span><em>BOUNDED</em></div><div className="telemetry-step"><b>03</b><span>GenLayer judgment</span><em>CONSENSUS</em></div><div className="telemetry-step"><b>04</b><span>Signed response</span><em>DELIVER</em></div></div>{result && <div className="result-window"><span>JOB OUTPUT</span><pre>{JSON.stringify(result, null, 2)}</pre></div>}</aside></div><div className="example-strip"><span>QUICK LOAD</span>{examples.map(example => <button key={example} onClick={() => setTask(example)}>{example}</button>)}</div></main>;
}
